DROP TABLE IF EXISTS tasks, clients, comments, black_list_refresh_tokens  CASCADE;

CREATE TABLE IF NOT EXISTS clients
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email  VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL,
    role  VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title  VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    status  VARCHAR(15),
    priority  VARCHAR(15),
    author_id BIGINT  REFERENCES clients(id) ON DELETE CASCADE NOT NULL,
    performer_id BIGINT  REFERENCES clients(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text  VARCHAR(100) NOT NULL,
    author_id BIGINT  REFERENCES clients(id) ON DELETE CASCADE NOT NULL,
    task_id BIGINT  REFERENCES tasks(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS black_list_refresh_tokens
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    jti  VARCHAR(100) NOT NULL
);